### ISSUE TITLE
Should navi provide more than listening capabilities?

### ISSUE THREAD

**Issue by dlew** [trello/navi#12]
In particular, I'm wondering about `Fragment.onCreateView()`. Obviously we can't have multiple listeners returning `Views`. However, if we don't at least provide the option then it's not possible to create an entirely listener-based `Fragment`.

My current thinking is "no" since this would make the library too complex, but I'm open to discussion.

**Comment by passsy** [comment]
As a first step I would not add the support to provide views with a `#onCreateView()` listener. Getting a callback when the event is happening is enough.

When adding the full create view support it could be solved with a convention: The first listener always wins. It should not throw when adding multiple `#onCreateView()` listeners but the returned view should just not be used. Additionally, print a warning.

**Comment by dlew** [comment]
I'm going to just say "no" to this for now. Coordinating multiple listeners would be a nightmare. I think it's probably best if we just limit this in scope.
