### ISSUE TITLE
Support for AppCompatDialogFragment

### ISSUE THREAD

**Issue by dalewking** [trello/navi#35]
Either the support version of NaviDialogFragment should extend AppCompatDialogFragment or else a NaviAppCompatDialogFragment should also exist.

**Comment by dlew** [comment]
That seems reasonable to me. I'm not sure which route we should go though. Is there a reason to use the v4 `DialogFragment` anymore? Or should one always use `AppCompatDialogFragment`?

**Comment by dalewking** [comment]
Not certain, but AppCompatDialogFragment only adds some styling things for AppCompatDialog so probably no reason to use v4 DialogFragment anymore. Here is the code for it:

https://github.com/android/platform_frameworks_support/blob/master/v7/appcompat/src/android/support/v7/app/AppCompatDialogFragment.java
