### ISSUE TITLE
Callbacks before and after super call

### ISSUE THREAD

**Issue by passsy** [trello/navi#36]
Libraries like [Flow](https://github.com/square/flow/blob/903bd3f9b02738babf7ea102a8604dfd220f1f1d/flow/src/main/java/flow/InternalLifecycleIntegration.java#L112) execute code before the `super` call. This is currently not supported by navi.

**Comment by dlew** [comment]
Do you have a proposal for how this would be supported?

**Comment by passsy** [comment]
The easiest solution would look like this. Two events for every lifecycle method, one before and one (the normal) after the `super` call.

NaviActivity
```java
  @Override protected void onResume() {
    base.onResumeBeforeSuper()
    super.onResume();
    base.onResume();
  }
```

NaviEmitter
```java
  public void onResumeBeforeSuper() {
    emitEvent(Event.RESUME_BEFORE_SUPER);
  }
```

### Possible problems
The ALL listener would run into problems. It's not possible to distinguish between the before and after events. //cc #30

**Comment by dlew** [comment]
That's the easy part, I meant more about how to modify the interface such that it doesn't make things a lot more complicated.

**Comment by passsy** [comment]
Not sure if I got this question correct.
The interface ([this?](https://github.com/trello/navi/blob/master/navi/src/main/java/com/trello/navi/Listener.java)) doesn't have to be tweaked for normal events. I don't see why more events make this lib more complicated. Simply register for whatever you need.

But the ALL listener requires this interface as proposed in #30.

```java
public interface AllListener<T> {
  void call(Event<T> event, T data);
}
```

**Comment by dlew** [comment]
Oh, so you mean a whole second set of events for before. Hmm... I'll have to think about it.

**Comment by dlew** [comment]
An alternative solution would be to allow you to specify it when adding the event, aka:

```java
<T> void addListener(Event<T> event, Listener<T> listener, boolean beforeSuper);
```

Then the event list would remain the same.

Adding a new parameter would make the API slightly more complex but maybe it's worth it for this flexibility.

**Comment by passsy** [comment]
All events I can think of have a super call. So, the optional `beforeSuper`(default: `false`) parameter is fine. Do you think there could be any kind of event where it doesn't make sense to use `beforeSuper: false`?

**Comment by dlew** [comment]
The more I think about this, the more I like it. Right now we're actually mixing when we call `super` - in most cases it's after, but in cases where a value is returned (e.g. `CREATE_VIEW`) we call it before.

I think requiring the specification of before/after super will make the API more flexible and more clear, since you don't have to wonder when it's being called in the lifecycle.

**Comment by cypressious** [comment]
Any news on this?

**Comment by dlew** [comment]
When I have spare time I'll be playing around with this more. I've got it half-baked over here.

**Comment by cypressious** [comment]
In my experience, all of the work in the destruction callbacks is usually done before the super call while the work in the creation callbacks is usually done after the super call. This is backed at least by this SO answer: http://stackoverflow.com/a/9626268/615306. I think Navi should do the same, no need for extra parameters and duplicate events.

**Comment by dlew** [comment]
Yeah, I think that's reasonable, as long as it's better documented.

The more I played around with the extra parameter, the more I got annoyed with it. It's just a lot of hassle for a corner case.

**Comment by passsy** [comment]
Calling the initializer `super` methods first and the finalizer methods after `super` is generally true. But some cases require doing something special, i.e. `setTheme()` normally gets called before `super.onCreate()`. And as @commonsguy said, it's up to the implementation logic when to call `super.onActivityResult()`.

 I'm really hoping navi will be general enough to get callbacks for both.

**Comment by dlew** [comment]
I thought you just needed to call `setTheme()` before `setContentView()`.
