### ISSUE TITLE
From "Events" to "States"

### ISSUE THREAD

**Issue by sahal2080** [trello/navi#37]
First thank you for a much-needed library. Coming from the Rails world, I can sincerely say that composition and global/local callbacks paradigms on Android can be, ah, bettered.

A suggestion I have is to add the capability of state/lifetime listeners. An obvious case would be [activity lifetimes](http://www.techotopia.com/index.php/Handling_Android_Activity_State_Changes#Activity_Lifetimes). For example, I already use something like this in my app: 
```java
@Override
public
boolean isVisible() {
  return activity_event.ordinal() >= ActivityEvent.START.ordinal() && activity_event.ordinal() < ActivityEvent.STOP.ordinal();
}
```
However, I think a much better implementation and a more powerful API this is added natively into navi.

**Comment by dlew** [comment]
Isn't this something that could be built on top of Navi, instead of being a part of Navi itself?

**Comment by passsy** [comment]
Yes it can be build on top of Navi. I've already created a class, monitoring `RESUME` and `PAUSE` for a simple `isResumed(): boolean` method because `Activity#isResumed()` is hidden from the public SDK.

**Comment by sahal2080** [comment]
Sure it can. However:
- Many comers to the Android world don't even know about these basic lifetimes as they're buried in documentation. Navi here can _inform_ and _perform_
- Looking at the other cool library RxLifecycle that you guys at Trello created, it's somewhat similar to what we're talking about except it solely focuses on rx. There might be an opportunity here for creating a general-purpose _intermediary_ layer to serve RxLifecycle and other applications, libraries, plugins, whatever..

**Comment by dlew** [comment]
RxLifecycle only cares about state incidentally, as a means of determining which event to use with `takeUntil`. Its primary focus is on binding a subscription until a lifecycle **event**.

Informing is not a goal of Navi. The goal is to solve a specific problem that I've run into many times. I'd like to keep Navi as lean as possible and have others build on top of it if possible.
