### ISSUE TITLE
is there anywhere I can see more examples of navi in use?

### ISSUE THREAD

**Issue by sirvon** [trello/navi#38]
I learn abstract concepts better by example.

This paradigm is different than that first learned in android development ( google's docs).

It would be powerfully useful if there were more examples of the ways this code can be
artfully constructed.

thank you for this library and your time.

**Comment by dlew** [comment]
There's a part of RxLifecycle that's based on Navi: https://github.com/trello/RxLifecycle/tree/master/rxlifecycle-navi

This is still an experimental library so I don't feel like writing a huge sample yet.
