### ISSUE TITLE
How do I register a NaviComponent early

### ISSUE THREAD

**Issue by eliasbagley** [trello/navi#49]
Hey - Navi looks awesome.
I'm having a conceptual difficulty when trying to use it to abstract saving and loading instance state though.

My Activities and Fragments are subclassing their respective NaviComponent - but how do I register these activities and fragments early enough in the Activity and Fragment lifecycle to listen for my onCreate events?

Basically, I'm not sure where in my app I should actually be calling `naviComponent.addListener()`. I can't do it in onCreate(), since that means the Navi listener will miss the first creation event, right?

I think I need some sort of "beforeCreate" callback somehow that exposes a NaviComponent so I can add listeners to it, but I don't think this is possible... Any help would be appreciated!

**Comment by mlatu** [comment]
What about instance initializer?

**Comment by eliasbagley** [comment]
@mlatu Can you give me an example? Activities are initialized by the framework so I'm not sure how I can hook into that.

**Comment by eliasbagley** [comment]
Ah I know what you mean. I can register it in my activity's zero argument constructor. Didn't think to do it in there, thanks! This issue can be closed. :+1:
