### ISSUE TITLE
Event.CREATE_VIEW in Fragment not received 

### ISSUE THREAD

**Issue by talenguyen** [trello/navi#55]
The event Event.CREATE_VIEW in Fragment will never received when we implement onCreateView and don't call the super.onCreateView().

**Comment by dlew** [comment]
That's pretty much unavoidable. You need to call `super()` or else the callback can't happen. There's nothing wrong with calling it in this case, since it does nothing.

**Comment by talenguyen** [comment]
Should we call that Event in onViewCreated() instead of onCreateView()?

**Comment by dlew** [comment]
That would also work. They're pretty much the same thing, just slightly different timing.
