### ISSUE TITLE
Add kotlin's DSL syntax for rx observing

### ISSUE THREAD

**Issue by georgeci** [trello/navi#58]
Like this https://gist.github.com/georgeci/d71cac374c3200ebb74e4beb6e968a8e
Using: https://gist.github.com/georgeci/8ac20864a98061d0504661fe9429ca79

**Comment by dlew** [comment]
I'm not familiar enough with Kotlin to really make the call on this one. That said, it's probably not a good idea for the lib to contain things that the maintainer doesn't know anything about... I'll look into this more when I've got a better grasp of Kotlin (working on it).

**Comment by dlew** [comment]
I'm going to close this for now because it's not directly actionable by me. Sorry.

**Comment by veyndan** [comment]
Considering you have now written multiple blog posts on Kotlin (which presumably means that you are comfortable with Kotlin), is there an updated response to @georgeci? Note that I haven't delved into the usefulness of @georgeci's code.

**Comment by dlew** [comment]
[Navi is deprecated and no longer being supported](https://github.com/trello/navi#deprecated), so it's sort of a moot point now.

**Comment by veyndan** [comment]
Note to self: read the README before commenting on an issue.
