### ISSUE TITLE
NaviFragment in ViewPager

### ISSUE THREAD

**Issue by elsennov** [trello/navi#65]
Hi @dlew , 

I have an issue regarding `NaviFragment`. So, i always call `takeUntil(RxNavi.observe(naviComponent, Event.DESTROY))` to avoid memory leak after subscribed to a view event from `NaviFragment`, like `Event.VIEW_CREATED`. 

This fragment is put inside ViewPager. My ViewPager consists of 3 or more `NaviFragment`, with `offScreenPageLimit`set to default (one).
I passed all fragments instance to the `FragmentStateAdapter` as final so the fragments will not always be created while switching the tab. 

My issue is, because of that, the constructor of the fragment will always be called once. So, all event in `NaviFragment` will not be subscribed anymore since i add `takeUntil(RxNavi.observe(naviComponent, Event.DESTROY))` to avoid memory leak. 
`Event.DESTROY` will be called if i switch the tab to the next/previous 2 tabs from current tab (`offScreenPageLimit` is one).

Do you have any suggestion for my issue? I want to keep the performance as high as possible but with no memory leak. Hehe, Thanks 👍

**Comment by dlew** [comment]
You should start your subscriptions in `onCreate()` instead of in the constructor. That way you know you're going to see `onDestroy()` as well.

**Comment by elsennov** [comment]
Ah, ok thanks!
