### ISSUE TITLE
Rx2: non-null savedInstanceState bundles

### ISSUE THREAD

**Issue by TillSimon** [trello/navi#84]
Events containing the savedInstanceState, like
`Event.CREATE`, `Event.CREATE_VIEW`
contain an empty bundle `Bundle[{}]` instead of `null`

**Comment by dlew** [comment]
RxJava 2 does not allow nulls to be emitted anymore, so we have to emit an empty Bundle instead. Read more here: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls

**Comment by TillSimon** [comment]
Yep, was about to comment right now when I realized that. Thanks for the quick reply.

**Comment by davidbilik** [comment]
And what about to send some Empty bundle instance that we can check against? Because in this way its not so straightforward to distinguish between first activity creation and restoring but with nothing in saved state bundle

**Comment by dlew** [comment]
You could check for the presence of specific keys in the bundle before using them.

**Comment by davidbilik** [comment]
Yes I know but its the "not so straightforward" way I was talking about :)
