### ISSUE TITLE
RxLifecycle needed to prevent leaks?

### ISSUE THREAD

**Issue by TillSimon** [trello/navi#89]
If I use
```
RxNavi.observe(naviComponent, Event.CREATE)
    .subscribe(bundle -> setContentView(R.layout.main));
```
do I still have to incl. RxLifecycle's
`.compose(RxLifecycle.bindUntilEvent(lifecycle, ActivityEvent.DESTROY))`
to avoid memory leaks?

(I assume `.compose(RxLifecycleAndroid.bindActivity(lifecycle))` wouldn't work if I'm subscribing in the constructor, so before the actual lifecycle starts?!)

**Comment by dlew** [comment]
Either that or unsubscribe. RxNavi just gives you a way to observe events.
