### ISSUE TITLE
Repeated support DialogFragment

### ISSUE THREAD

**Issue by veyndan** [trello/navi#90]
[`support/NaviDialogFragment`](https://github.com/trello/navi/blob/2.x/navi/src/main/java/com/trello/navi2/component/support/NaviDialogFragment.java) and [`support/NaviAppCompatDialogFragment`](https://github.com/trello/navi/blob/2.x/navi/src/main/java/com/trello/navi2/component/support/NaviAppCompatDialogFragment.java) are identical. Is there any purpose to this?

**Comment by dlew** [comment]
Whoops, that's a mistake. One should be extending AppCompatDialogFragment.
